[package]
name = "astro_inventory"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.6", features = ["set-header"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["std", "clock"] }
regex = "1"
reqwest = { version = "0.12", features = ["json", "blocking"] }
maxminddb = "0.31"
clap = { version = "4", features = ["derive"] }
anyhow = "1"
percent-encoding = "2"

[profile.prof]
inherits = "release"
debug = true
